#!/usr/bin/env bash
set -ex

export PATH="/opt/cellranger-7.1.0:$PATH"

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
bash cellranger.sh "$@"
